config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  root to: 'top#index'
  resources :top, only: :index

  devise_for(
    # deviseのモデル
    :users,
    # deviseで生成するURLの基準となるパス
    path: 'settings',
    # deviseのコントローラがあるディレクトリ
    module: 'users'
  )

  # deviseにルーティングを追加する
  devise_scope :user do
    get '/login', to: 'users/sessions#new'
    get '/sign_up', to: 'users/registrations#new'
  end

  resources :user_profiles, path: 'settings', only: [] do
    get '/profile', to: 'user_profiles#edit', on: :member
    patch '/profile', to: 'user_profiles#update', on: :member
  end

  resources :rooms, only: %i(index show) do
    post '/create', to: 'rooms#create', on: :collection
    get '/create', to: 'rooms#new', on: :collection
  end

  resources :room_search_forms, only: :index do
    get 'area_search', on: :collection
  end

  resources :reservations do
    get 'registered', on: :member
    get 'completed', on: :collection
  end

  resources :reservation_hosts, path: 'hosts', only: %i(index show update) do
    get 'completed', on: :collection
  end

  resources :notifications, only: :index

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :guest, class_name: 'User'
  belongs_to :host, class_name: 'User'
  belongs_to :reservation

  scope :action_unchecked,
    -> (action:) {
      where(action: action).
        where(checked: false)
    }

  scope :to_do_notifications,
    -> (guest_id:, host_id:, cancel_request:, reserve:, cancel:) {
      where('guest_id = ? and action = ?', guest_id, cancel_request).
        or(where('host_id = ? and action = ?', host_id, reserve)).
        or(where('host_id = ? and action = ?', host_id, cancel))
    }

  def unchecked_count_or_false_if_zero(user_id:)
    notifications = Notification.to_do_notifications(
      guest_id: user_id,
      host_id: user_id,
      cancel_request: "cancel_request",
      reserve: "reserve",
      cancel: "cancel"
    ).
      where(checked: false)

    return notifications.size if notifications.exists?
    false
  end

  def has_user_as_host?(user_id:)
    host_id == user_id
  end

  def has_user_as_guest?(user_id:)
    guest_id == user_id
  end

  def checked?
    checked
  end

  def has_action?(**actions)
    if action == actions[:cancel_request] ||
                   action == actions[:cancel] ||
                   action == actions[:reserve]
      return true
    end

    false
  end

  def has_action_for_host?(user_id:, **actions)
    reserve = actions[:reserve] || ''
    cancel = actions[:cancel] || ''

    if has_user_as_host?(user_id: user_id) && has_action?(reserve: reserve, cancel: cancel)
      return true
    end

    false
  end

  def has_action_for_guest?(user_id:, **actions)
    cancel_request = actions[:cancel_request] || ''

    if has_user_as_guest?(user_id: user_id) && has_action?(cancel_request: cancel_request)
      return true
    end

    false
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.to_do_notifications(
      guest_id: current_user.id,
      host_id: current_user.id,
      cancel_request: "cancel_request",
      reserve: "reserve",
      cancel: "cancel"
    ).
      order(created_at: 'DESC').
      includes(guest: { image_attachment: :blob }, host: { image_attachment: :blob })
  end
end

app/views/notifications/index.html.erb
<% content_for(:title, "お知らせ") %>
<% content_for :switch_stylesheets do %>
  .first::before {
    content: "";
    background-color: rgba(237, 5, 5, 0.826);
    border-radius: 2px;
    height: 4px;
    position: absolute;
    bottom: 0px;
    left: 0px;
    width: 100%;
  }
<% end %>

<div class="lists-container"> 
  <h1>お知らせ</h1>
  <div class="lists-wrapper">
    <div class="tab-menu"> 
      <%= link_to notifications_path do %>
        <div class="tab-item first">
          <span>やることリスト</span>
        </div>
      <% end %>
    </div>
    <% @notifications.each do |notification| %>
      <% if notification.has_action_for_host?(user_id: current_user.id, reserve: 'reserve', cancel: 'cancel') %>
        <%= link_to reservation_host_path(notification.reservation_id) do %>
          <div class="notification-list">
            <%= image_tag notification.guest.image, class: 'notification-list-image' if notification.guest.image.attached? %>
            <div class="notification-list-headline">
              <div class="notification-list-main">
                <i class="<%= "fa-solid fa-exclamation" if !notification.checked? %>"></i>
                <%= notification.guest.name %>
                <% if notification.has_action?(reserve: 'reserve') %>
                  <span class="comment">さんがあなたの物件を予約しました。予約内容を確認してください。</span>
                <% elsif notification.has_action?(cancel: 'cancel') %>
                  <span class="comment">さんが予約をキャンセルしました。予約内容を確認してください。</span>
                <% end %>
              </div>
              <div class="notification-list-bottom">
                <span><%= time_ago_in_words(notification.created_at) %></span>
                <span class="ago">前</span>
              </div>
            </div>
            <div class="chevron-container">
              <i class="fa-solid fa-chevron-right"></i>
            </div>
          </div>
        <% end %>
      <% elsif notification.has_action_for_guest?(user_id: current_user.id, cancel_request: 'cancel_request') %>
        <%= link_to reservation_path(notification.reservation_id) do %>
          <div class="notification-list">
            <%= image_tag notification.host.image, class: 'notification-list-image' if notification.guest.image.attached? %>
            <div class="notification-list-headline">
              <div class="notification-list-main">
              <i class="<%= "fa-solid fa-exclamation" if !notification.checked? %>"></i>
                <span class="comment">ホストからキャンセルリクエストがありました。この予約のキャンセルをお願い致します。</span>
              </div>
              <div class="notification-list-bottom">
                <span><%= time_ago_in_words(notification.created_at) %></span>
                <span class="ago">前</span>
              </div>
            </div>
            <div class="chevron-container">
              <i class="fa-solid fa-chevron-right"></i>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>