config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  root to: 'top#index'
  resources :top, only: :index

  devise_for(
    # deviseのモデル
    :users,
    # deviseで生成するURLの基準となるパス
    path: 'settings',
    # deviseのコントローラがあるディレクトリ
    module: 'users'
  )

  # deviseにルーティングを追加する
  devise_scope :user do
    get '/login', to: 'users/sessions#new'
    get '/sign_up', to: 'users/registrations#new'
  end

  resources :user_profiles, path: 'settings', only: [] do
    get '/profile', to: 'user_profiles#edit', on: :member
    patch '/profile', to: 'user_profiles#update', on: :member
  end

  resources :rooms, only: %i(index show) do
    post '/create', to: 'rooms#create', on: :collection
    get '/create', to: 'rooms#new', on: :collection
  end

  resources :room_search_forms, only: :index do
    get 'area_search', on: :collection
  end

  resources :reservations do
    get 'registered', on: :member
    get 'completed', on: :collection
  end

  resources :reservation_hosts, path: 'hosts', only: %i(index show update) do
    get 'completed', on: :collection
  end

  resources :notifications, only: :index

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error.html.erb
<% if resource.errors.any? %>
  <% resource.errors.full_messages.each do |message| %>
      <ul>
        <li><%= safe_join(message.split("\n"), tag(:br)) %></li>
      </ul>
  <% end %>
<% end %>

app/views/shared/_flash_error.html.erb
<% flash["errors"]&.each do |message| %>
  <ul>
    <li><%= safe_join(message.split("\n"), tag(:br)) %></li>
  </ul>
<% end %>

app/views/shared/_guest_tab_menu.html.erb
<div class="tab-menu"> 
  <%= link_to reservations_path do %>
    <div class="tab-item first">
      <i class="<%= "fa-solid fa-exclamation" if current_user.has_reservations_cancel_requested? %>"></i>
      <span>予約中</span>
    </div>
  <% end %>
  <%= link_to completed_reservations_path do %>
    <div class="tab-item second">
      <span>予約履歴</span>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="header-container">
    <%= link_to root_path, class: "site-title" do %>
      Life<span>in</span>Pocket
    <% end %>
    <%= search_form_for @q, url: room_search_forms_path, class: "search-form" do |f| %>
      <div class="map-icon-field">
        <%= f.search_field :adress_cont, placeholder: "エリア", class: "adress-search-field" %>
        <i class="fa-solid fa-location-dot"></i>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="user-field-container">
      <div class="notification-field">
        <%= link_to notifications_path do %>
          <i class="fa-solid fa-bell"></i>
          <% if @notification.unchecked_count_or_false_if_zero(user_id: current_user.id) %>
            <div class="notification-number">
              <span><%= @notification.unchecked_count_or_false_if_zero(user_id: current_user.id) %></span>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="user-icon-field"> 
        <% if current_user.image.attached? %>
          <%= image_tag current_user.image, class: 'user-icon' %>
        <% else %>
          <%= image_tag "/assets/default_icon.jpg" , class: 'user-icon' %>
        <% end %>
      </div>
    </div>
    <ul class="global-navigation hide-element">
      <%= link_to create_rooms_path do %>
        <div class="navigation-list-container">
          <div class="navigation-list">
            <li>物件登録</li>
            <div class="chevron-container">
              <i class="fa-solid fa-chevron-right"></i>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to edit_user_registration_path do %>
        <div class="navigation-list-container">
          <div class="navigation-list">
            <li>マイページ</li>
            <div class="chevron-container">
              <i class="fa-solid fa-chevron-right"></i>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to reservation_hosts_path do %>
        <div class="navigation-list-container">
          <div class="navigation-list">
            <li>ホストページ</li>
            <div class="chevron-container">
              <i class="fa-solid fa-chevron-right"></i>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to reservations_path do %>
        <div class="navigation-list-container">
          <div class="navigation-list">
            <li>ゲストページ</li>
            <div class="chevron-container">
              <i class="fa-solid fa-chevron-right"></i>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: "logout" do %>
        <div class="navigation-list-container">
          <div class="navigation-list">
            <li>ログアウト</li>
            <div class="chevron-container">
              <i class="fa-solid fa-chevron-right"></i>
            </div>
          </div>
        </div>
      <% end %>
  <% else %>
    <div class="entry-field">
      <%= link_to 'ログイン', login_path %>
      <%= link_to '登録する', sign_up_path %>
    </div>
  <% end %>
</header>

app/views/shared/_host_tab_menu.html.erb
<div class="tab-menu"> 
  <%= link_to reservation_hosts_path do %>
    <div class="tab-item ongoing">
    <i class="<%= "fa-solid fa-exclamation" if current_user.has_reservations_cancel_requested? || current_user.has_notifications_unchecked_as_host?(action: "reserve") %>"></i>
      <span>受付中</span>
    </div>
  <% end %>
  <%= link_to completed_reservation_hosts_path do %>
    <div class="tab-item history">
      <i class="<%= "fa-solid fa-exclamation" if current_user.has_notifications_unchecked_as_host?(action: "cancel") %>"></i>
      <span>予約履歴</span>
    </div>
  <% end %>
  <%= link_to rooms_path do %>
    <div class="tab-item rooms">
      <span>物件一覧</span>
    </div>
  <% end %>
</div>

app/views/shared/_reservation_lists.html.erb
<div class="reservation-list <%= "cancel-item" if reservation.cancel_completed?(user_id: current_user.id) %>">
  <%= image_tag reservation.room.room_image, class: 'reservation-list-image' if reservation.room.room_image.attached? %>
  <div class="reservation-list-headline">
    <div class="reservation-list-name">
      <i class="<%= "fa-solid fa-exclamation" if reservation.cancel_requested? || reservation.has_notifications_unchecked_by_host?(user_id: current_user.id, reserve: 'reserve', cancel: 'cancel') %>"></i>
      <%= reservation.room.name %>
    </div>
    <div class="reservation-list-date">
      <span><%= reservation.checkin.strftime("%Y/%m/%d") %></span>
      <span>~</span>
      <span><%= reservation.checkout.strftime("%Y/%m/%d") %></span>
    </div>
  </div>
  <div class="reservation-chevron-container">
    <i class="fa-solid fa-chevron-right"></i>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search-results-container"> 
  <div>
    <h2 class="search-count">検索結果：<%= rooms.size %>件</h2>
    <div class="search-boxes-wrapper">
      <% rooms.each do |room| %>
        <div class="search-box">
          <%= link_to(room_path(room), target: "_blank", rel: "noopener") do %>
            <%= image_tag room.room_image, class: 'search-box-image' if room.room_image.attached? %>
            <div class="seach-box-intro">
              <div class="seach-box-name">
                <p><%= room.name %></p>
              </div>
              <p class="seach-box-adress"><%= room.adress %></p>
              <p class="search-box-fee">￥<%= room.fee.to_s(:delimited) %>/日</p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="search-results-pagenation">
    <%= paginate rooms %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <nav>
    <div class="sidebar-lists-container">
      <ul>
        <li class="sidebar-account"><%= link_to 'アカウント設定', edit_user_registration_path %></li>
        <li class="sidebar-profile"><%= link_to 'プロフィール情報', profile_user_profile_path(current_user.id) %></li>
      </ul>
    </div>
  </nav>
</div>